name: Build website on PR

on:
  pull_request

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Build only 
      uses: shalzz/zola-deploy-action@v0.18.0
      env:
        BUILD_DIR: src
        BUILD_ONLY: true

    - name: Compress website
      run: |
        cd src
        tar -czf website.tar.gz public
        tar -tf website.tar.gz

    - name: Verify that the tar file is created
      run: |
        ls src | grep website.tar.gz
