name: Build and attach website to release

on:
  push:
    tags:
      - '*'

jobs:
  build:
    name: Publish binaries
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Setup Hugo
      uses: peaceiris/actions-hugo@v2
      with:
        hugo-version: '0.115.0'
        extended: true

    - name: Build website
      run: |
          cd $GITHUB_WORKSPACE/src
          hugo -t hugo-winston-theme --minify

    - name: Compress website
      run: |
        cd $GITHUB_WORKSPACE/src/public
        tar -czf website.tar.gz .
        tar -tf website.tar.gz

    - name: Upload binaries to release
      uses: svenstaro/upload-release-action@v2
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: website.tar.gz
        asset_name: website.tar.gz
        tag: ${{ github.ref }}
        overwrite: true
