name: Build and attach website to release

on:
  push:
    tags:
      - '*'

jobs:
  build:
    name: Publish binaries
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Setup Hugo
      uses: peaceiris/actions-hugo@v2
      with:
        hugo-version: '0.115.0'
        extended: true

    - name: Build only 
      working-dir: src
      uses: shalzz/zola-deploy-action@v0.18.0
      env:
        BUILD_DIR: .
        BUILD_ONLY: true

    - name: Compress website
      working-dir: src
      run: |
        tar -czf website.tar.gz public
        tar -tf website.tar.gz
        mv website.tar.gz $GITHUB_WORKSPACE

    - name: Upload binaries to release
      uses: svenstaro/upload-release-action@v2
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: website.tar.gz
        asset_name: website.tar.gz
        tag: ${{ github.ref }}
        overwrite: true
