name: Build and attach website to release

on:
  push:
    branches: [ main ]
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    name: Build and release website
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      # Zola build only; no Hugo needed
      - name: Build site with Zola
        uses: shalzz/zola-deploy-action@v0.18.0
        env:
          BUILD_DIR: src
          BUILD_ONLY: true

      - name: Compute release date (UTC)
        run: echo "RELEASE_DATE=$(date -u +%F)" >> $GITHUB_ENV

      - name: Archive website
        run: |
          tar -czf website.tar.gz -C src public
          tar -tf website.tar.gz | head -n 10

      - name: Create GitHub Release and upload asset
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: website.tar.gz
          asset_name: website.tar.gz
          tag: ${{ env.RELEASE_DATE }}
          release_name: ${{ env.RELEASE_DATE }}
          overwrite: true
          body: |
            Static site build for ${{ env.RELEASE_DATE }}.
            - Base URL: https://wachs.work
            - Built with Zola from src/
